jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"
jobs:
  - script: >
      folder('develop')
  - script: >
      pipelineJob("develop/JOB-Servers") {
          description("JOB-Servers")
          parameters {
            stringParam("PREFIX", "prefix", "your description here")
            choiceParam('SIZE', ['Ds2 (default)', 'Ds4', 'Ds8'])
          }
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              github("aldenso/terraform-pipeline-test", "https")
                              credentials("github-user")
                          }
                          branch("*/main")
                      }
                  }
                  scriptPath("devops/dev/Jenkinsfile.groovy")
              }
          }
          disabled(false)
      }
